/* Auto-generated by genmsg_cpp for file /home/robo/ros_workspace/robot/sharps/msg/Distance.msg */
#ifndef SHARPS_MESSAGE_DISTANCE_H
#define SHARPS_MESSAGE_DISTANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace sharps
{
template <class ContainerAllocator>
struct Distance_ {
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
  : header()
  , rear(0.0)
  , front(0.0)
  , rear_r(0.0)
  , front_r(0.0)
  , rear_l(0.0)
  , front_l(0.0)
  {
  }

  Distance_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , rear(0.0)
  , front(0.0)
  , rear_r(0.0)
  , front_r(0.0)
  , rear_l(0.0)
  , front_l(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _rear_type;
  float rear;

  typedef float _front_type;
  float front;

  typedef float _rear_r_type;
  float rear_r;

  typedef float _front_r_type;
  float front_r;

  typedef float _rear_l_type;
  float rear_l;

  typedef float _front_l_type;
  float front_l;


  typedef boost::shared_ptr< ::sharps::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sharps::Distance_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Distance
typedef  ::sharps::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::sharps::Distance> DistancePtr;
typedef boost::shared_ptr< ::sharps::Distance const> DistanceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sharps::Distance_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sharps::Distance_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sharps

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sharps::Distance_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sharps::Distance_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sharps::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "939ab581b431e3c1c016caf7e25338fb";
  }

  static const char* value(const  ::sharps::Distance_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x939ab581b431e3c1ULL;
  static const uint64_t static_value2 = 0xc016caf7e25338fbULL;
};

template<class ContainerAllocator>
struct DataType< ::sharps::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sharps/Distance";
  }

  static const char* value(const  ::sharps::Distance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sharps::Distance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 rear\n\
float32 front\n\
float32 rear_r\n\
float32 front_r\n\
float32 rear_l\n\
float32 front_l\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::sharps::Distance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sharps::Distance_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sharps::Distance_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sharps::Distance_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.rear);
    stream.next(m.front);
    stream.next(m.rear_r);
    stream.next(m.front_r);
    stream.next(m.rear_l);
    stream.next(m.front_l);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Distance_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sharps::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sharps::Distance_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rear: ";
    Printer<float>::stream(s, indent + "  ", v.rear);
    s << indent << "front: ";
    Printer<float>::stream(s, indent + "  ", v.front);
    s << indent << "rear_r: ";
    Printer<float>::stream(s, indent + "  ", v.rear_r);
    s << indent << "front_r: ";
    Printer<float>::stream(s, indent + "  ", v.front_r);
    s << indent << "rear_l: ";
    Printer<float>::stream(s, indent + "  ", v.rear_l);
    s << indent << "front_l: ";
    Printer<float>::stream(s, indent + "  ", v.front_l);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SHARPS_MESSAGE_DISTANCE_H

